# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml
name           = "mindy"
description = """
Tinydns on a blockchain! Mindy extends djb's tinydns by updating the zone file with records fetch from a blockchain

This eris service currently uses a tendermint chain as its consensus engine.

See the testnet at: pinkpenguin.interblock.io:46657/list_names
"""

status = "alpha"


chain 	       = "$chain:chain:l"

[service]
name           = "mindy"
image          = "quay.io/eris/mindy"
environment    = [ "UPDATE_EVERY=5" ]

[dependencies]
services = ["tinydns::v"]

[maintainer]
name = "Ethan Buchman"
email = "ethan@erisindustries.com"

[location]
dockerfile = "https://github.com/eris-ltd/mindy/blob/master/Dockerfile"
repository = "https://github.com/eris-ltd/mindy"
website = "https://github.com/eris-ltd/mindy/wiki"
